articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('home/',views.article_page,name='new_home'),
    path('<slug:slug>',views.article_detail,name='detail')
]

backend/urls.py
from django.contrib import admin

from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('',include('articles.urls',namespace='articles')),
    path('',include('account.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # Displaying all date to be read
    path('missing_people/', views.missing_people, name='missing_people'),
    path('wanted_people/', views.wanted_people, name='wanted_people'),
    # selected persons
    path('person_of_intrest/<str:pk>', views.person_of_intrest, name='POI'),
    path('missing_person/<str:pk>', views.missing_pep, name='missing_person'),
    # create
    path('adding_missing_person', views.add_missing_person,
         name="adding_missing_person"),
    path('adding_wanted_person', views.add_wanted_person,
         name="adding_wanted_person"),
    # update
    path('updating_missing_person/<str:pk>/',
         views.update_missing, name="update_missing"),
    path('updating_wanted_person/<str:pk>/',
         views.update_wanted, name="update_wanted"),
    # delete
    path('remove_wanted_person/<str:pk>/',
         views.remove_wanted, name="remove_wanted"),
    path('remove_missing_person/<str:pk>/',
         views.remove_missing, name="remove_missing"),
    # login
    
]

articles/models.py
from email.policy import default
from django.db import models

# Create your models here.
class Categories(models.Model):
    
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

articles/views.py
from unicodedata import category
from django.shortcuts import render
from .models import Categories

# Create your views here.
def article_page(request):
    cartegories = Categories.objects.all()
    context = {
        'cartegories':cartegories
    }
    return render(request,'articles/main_page.html',context)


def article_detail(request,slug):
    cartegory = Categories.objects.get(slug=slug)
    context = {
        'cartegory':cartegory
    }
    return render(request,'articles/details_page.html',context)

articles/templates/articles/details_page.html
{% extends 'main.html' %}
{% block content %}

<h1>{{cartegory.name}}</h1>
<p>{{cartegory.body}}<p>
{% endblock content %}

articles/templates/articles/main_page.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<h1>welcome to home</h1>
<div class="block-container">
    <div class="block-items">
            {% for cartegory in cartegories %}
            <div class="block-item">
                
                <div class="block-img" style="background-image:url({% static 'img/portfolio8.jpg' %});"></div>
                <div class="block-text">
                    <div class="block-title">
                        <p>{{cartegory.name}}</p>
                    </div>
                    <div class="block-link">
                        <a href="{% url 'articles:detail' slug=cartegory.slug %}">See More</a>
                    </div>
                </div>
            </div>
{% endfor %}
        </div>
    </div>
{% endblock content %}