articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('home/',views.article_page,name='new_home'),
    path('<slug:slug>',views.article_detail,name='detail')
]

backend/urls.py
from django.contrib import admin

from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('',include('articles.urls',namespace='articles')),
    path('',include('account.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # Displaying all date to be read
    path('missing_people/', views.missing_people, name='missing_people'),
    path('wanted_people/', views.wanted_people, name='wanted_people'),
    # selected persons
    path('person_of_intrest/<str:pk>', views.person_of_intrest, name='POI'),
    path('missing_person/<str:pk>', views.missing_pep, name='missing_person'),
    # create
    path('adding_missing_person', views.add_missing_person,
         name="adding_missing_person"),
    path('adding_wanted_person', views.add_wanted_person,
         name="adding_wanted_person"),
    # update
    path('updating_missing_person/<str:pk>/',
         views.update_missing, name="update_missing"),
    path('updating_wanted_person/<str:pk>/',
         views.update_wanted, name="update_wanted"),
    # delete
    path('remove_wanted_person/<str:pk>/',
         views.remove_wanted, name="remove_wanted"),
    path('remove_missing_person/<str:pk>/',
         views.remove_missing, name="remove_missing"),
    # login
    
]

templates/main.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vimba</title>
    <!-- style sheet -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}" />
  </head>
  <body>
    <div class="container">
      {% include 'nav.html' %} 
      <div class="section">
        <div class="section-wrapper">
      {% block content %}{% endblock content %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/nav.html
<!-- header navigation -->
      <div class="header-wrapper">
        <!-- logo -->
        <div class="header-logo">
          {% if request.user.is_authenticated %}
          <a href="{% url 'articles:new_home' %}">vimba</a>
          {% else%}
          <a href="{% url 'home' %}">vimba</a>
          {%endif%}
        </div>
        <!-- navigation -->
        <div class="header-nav">
          <div class="nav-item">
            <a href="{% url 'wanted_people' %}">wantedPeople</a>
          </div>
          <div class="nav-item">
            <a href="{% url 'missing_people' %}">missingPeople</a>
          </div>
          
          <div class="nav-item">
            {% if request.user.is_authenticated %}
            <a style='color:black'>hello {{request.user}}<a>
            <a href="{% url 'logout' %}">logout</a>
            {%else%}
            <a href="{% url 'login' %}">login</a>
            {% endif %}
          </div>
        </div>
      </div>